### PR TITLE
fix position of `--` arg to npx

### LINKED ISSUE #11: Warning caused by wrong argument passed to pyright by the wrapper script
Running the `pyright` bin installed from this module causes the following call to `npx`:

```sh
npx --silent --yes pyright@1.1.190
```

If an argument is present (e.g. `pyright foo`) this changes to:

```sh
npx --silent --yes pyright@1.1.190 -- foo
```

This causes the following warning from pyright:

```
File or directory "/Users/tim/repos/github.com/smb-ag/reels/--" does not exist.
```

This is because the `--` is passed from `npx` to `pyright` where it is not handled in the typical gnunix way and instead understood as the first "file" argument to pyright.
As per [npx docs](https://docs.npmjs.com/cli/v8/commands/npx) the correct call should be:
(using `npm exec -- <pkg>[@<version>] [args...]` syntax)

```sh
npx --silent --yes -- pyright@1.1.190 foo
```

### PR DESCRIPTION
**Pull request by bustbr**
fixes #11

### CODE REVIEW

**Comment by RobertCraigie** [comment]
I'm going to disable codecov status checks before merging this commit.

I've had issues with it in the past, see the commits for https://github.com/RobertCraigie/prisma-client-py/pull/148#issuecomment-977256410.

**Comment by RobertCraigie** [comment]
@bustbr Would it be possible for you to write a unit test in `tests/test_main.py` and ensure the test correctly catches the issue please.

I can't replicate the issue on my machine so it is not possible for me to write an accurate test.

Thank you!

**Comment by RobertCraigie** [comment]
Thank you!

**Comment by bustbr** [comment]
> ~@bustbr Would it be possible for you to write a unit test in `tests/test_main.py` and ensure the test correctly catches the issue please.~

@RobertCraigie ah, I wasn't sure how best to test it, I [created a branch where I extracted the building of the command arguments](https://github.com/RobertCraigie/pyright-python/compare/main...bustbr:test-npx-cmd) into a separate function. is that of any use to you?

**Comment by RobertCraigie** [comment]
Yes that would be useful, thank you!

I have no idea how to fix this issue, it occurs on my local machine but does not on CI :/

**Comment by bustbr** [comment]
> I have no idea how to fix this issue, it occurs on my local machine but does not on CI :/

Oh, you know what, I took another look at the documentation. for `npx` it actually gives a different syntax than for `npm exec`! I assume it depends on the version of both `npm` and `npx` then which call causes the issue.

For npm the docs say
```
npx <pkg>[@<specifier>] [args...]
npx -p <pkg>[@<specifier>] <cmd> [args...]
```

So if _you_ call something like `npx --silent --yes -- pyright@1.1.190 .` from a shell directly you can reproduce the error, yes? For me this works without error, but so does `npx --silent --yes -p pyright@1.1.190 -- pyright .` (which would be the second line from the docs), so if that also works for you we could switch to that.
Or we could just remove the `--` altogether because apparently `npx` just doesn't want it, so `npx --silent --yes pyright@1.1.190 .` – also works without errors for me, and any further args are being passed on to `pyright`, including any `--`, which is exactly what we want anyway I think.

**Comment by RobertCraigie** [comment]
@bustbr Thank you for your very detailed investigation!

I still don't know what was causing my issue but re-installing the package fixed it and internally running `npx --silent --yes -- pyright@1.1.190 foo.py` works without any warnings.

As it's not documented we should look into dropping the `--` separator. 

However, the tests / CI for this package are not up to scratch, I am wary of completely removing the `--` without extensive cross-platform and cross-version tests.

Before removing the `--` we should:

- [ ] Test windows and MacOS on CI
- [ ] Test multiple node versions on CI
- [ ] Write extensive unit / integration tests

**Pull request merged**
